import Head from 'next/head'
import Image from "next/image";
import "../styles/Home.module.css";

export default function Home() {
  const buttons = Array(10).fill(0);
  return (
    // <div className={styles.container}>
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className={styles.main}> */}
      <main className="m-h-screen p-16 flex-1 flex-coli justify-center items-center">
        <div className="text-center text-green text-lg">Testing</div>
        <div className="flex justify-center items-center my-9">
          {buttons.map((_, idx) => (
            <button
              key={idx}
              className="p-3 mx-2 bg-green-600 border-green-800 border-b rounded-xl hover:bg-gray-600 text-green-200 font-bold"
            >{`Button ${idx + 1}`}</button>
          ))}
        </div>
      </main>

      <footer className="flex flex-1 justify-center items-center p-8 border-t-black">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="flex flex-grow justify-center items-center"
        >
          Powered by{" "}
          <span className="">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
